name: 'Get list of pull requests'
description: 'Lists pull requests for a specified branch'
inputs:
  base:
    description: 'Base branch to list pull requests for'
    required: true
    default: 'master'
  state:
    description: 'The state of the pull requests to list'
    required: false
    default: 'open'
  hours_old:
    description: 'Filter out PRs that are more than this many hours old (0 means no filtering)'
    required: false
    default: '0'
  github-token:
    description: 'GitHub token for authentication'
    required: true
    default: ${{ github.token }}
outputs:
  pull_requests_json:
    description: 'JSON array containing the pull request data'
  count:
    description: 'Number of pull requests found'
runs:
  using: 'node16'
  main: 'dist/index.js' 